/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kz.kstu.coursework;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author j3t1x
 */
public class AdminMenu extends javax.swing.JFrame {
JTextField[] textFields =null;
JScrollPane scrollPane = null;
JTable table = new JTable();
Connection connection=null;
int columns =1;
    /**
     * Creates new form AdminMenu
     */
    public AdminMenu(String login,String password) {
        connection = SqlConnection.Connect(login,password);
        setLocation(500,200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        UsersButton = new javax.swing.JButton();
        AuditButton = new javax.swing.JButton();
        BackUpButton = new javax.swing.JButton();
        ErLabel = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        FullRB = new javax.swing.JRadioButton();
        TempRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UsersButton.setText("Users");
        UsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButtonActionPerformed(evt);
            }
        });

        AuditButton.setText("Audit log");
        AuditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuditButtonActionPerformed(evt);
            }
        });

        BackUpButton.setText("Back up");
        BackUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackUpButtonActionPerformed(evt);
            }
        });

        ErLabel.setForeground(new java.awt.Color(204, 51, 0));
        ErLabel.setText("                     ");

        InsertButton.setText("Insert");
        InsertButton.setEnabled(false);

        UpdateButton.setText("Update");
        UpdateButton.setEnabled(false);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.setEnabled(false);

        FullRB.setText("FullBackUp");
        FullRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullRBActionPerformed(evt);
            }
        });

        TempRB.setText("TempBackUp");
        TempRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(InsertButton)
                        .addGap(40, 40, 40)
                        .addComponent(UpdateButton)
                        .addGap(39, 39, 39)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(UsersButton)
                        .addGap(52, 52, 52)
                        .addComponent(AuditButton)
                        .addGap(37, 37, 37)
                        .addComponent(BackUpButton)
                        .addGap(18, 18, 18)
                        .addComponent(FullRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TempRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(184, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsersButton)
                    .addComponent(AuditButton)
                    .addComponent(BackUpButton)
                    .addComponent(FullRB)
                    .addComponent(TempRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InsertButton)
                        .addComponent(UpdateButton)
                        .addComponent(DeleteButton)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButtonActionPerformed
        int xx = 0;
        String tableName = "select * from Users";
        table.setBounds(30,70,600,300);
            try {table.setModel(SqlConnection.buildTableModel(tableName,connection));
            } catch (SQLException ex) {
            Logger.getLogger(HODMenu.class.getName()).log(Level.SEVERE, null, ex);}
        if(scrollPane==null){
        sp(table);
        }
        if(textFields!=null){
        tfdel();
        columns = table.getColumnCount();
        textFields = new JTextField[columns];
        for(int k = 0; k<columns; k++){
        textFields[k]= new JTextField();
        panel1.add(textFields[k]);
        textFields[k].setBounds(20+xx,400,90,25);
        xx=xx+120;}
        }
        if(textFields ==null){
            columns = table.getColumnCount();
        textFields = new JTextField[columns];
        for(int k = 0; k<columns; k++){
        textFields[k]= new JTextField();
        panel1.add(textFields[k]);
        textFields[k].setBounds(20+xx,400,90,25);
        xx=xx+120;
        ErLabel.setText("");
        }}
        InsertButton.setEnabled(true);
        UpdateButton.setEnabled(true);
        DeleteButton.setEnabled(true);
    }//GEN-LAST:event_UsersButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void AuditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuditButtonActionPerformed
        
        String query = "EXEC xp_readerrorlog 0, 1, N'Failed'";
        table.setBounds(30,70,550,300);
            try {table.setModel(SqlConnection.buildTableModel(query,connection));
            } catch (SQLException ex) {
            Logger.getLogger(HODMenu.class.getName()).log(Level.SEVERE, null, ex);}
            if(textFields!=null){tfdel();}
        if(scrollPane==null){
        sp(table);}
        InsertButton.setEnabled(false);
        UpdateButton.setEnabled(false);
        DeleteButton.setEnabled(false);
    }//GEN-LAST:event_AuditButtonActionPerformed

    private void BackUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackUpButtonActionPerformed
        InsertButton.setEnabled(false);
        UpdateButton.setEnabled(false);
        DeleteButton.setEnabled(false);
    }//GEN-LAST:event_BackUpButtonActionPerformed

    private void FullRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullRBActionPerformed
        TempRB.setSelected(false);
    }//GEN-LAST:event_FullRBActionPerformed

    private void TempRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempRBActionPerformed
        FullRB.setSelected(false);
    }//GEN-LAST:event_TempRBActionPerformed

    
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminMenu().setVisible(true);
            }
        });
    }
public void sp(JTable table){
scrollPane = new JScrollPane(table);
        scrollPane.setBounds(30,70,600,300);
        panel1.add(scrollPane);}


public  void tfdel(){
for (int i = 0; i < textFields.length; i++) {
    if(textFields[i]!=null){
                textFields[i].hide();
        panel1.remove(textFields[i]);
        textFields[i]=null;
        }}}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuditButton;
    private javax.swing.JButton BackUpButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel ErLabel;
    private javax.swing.JRadioButton FullRB;
    private javax.swing.JButton InsertButton;
    private javax.swing.JRadioButton TempRB;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UsersButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
